FROM fedora:latest

ARG USERNAME=sqwxl
ARG UID=1000
ARG GID=$UID

RUN dnf install -y sudo

RUN groupadd --gid $GID $USERNAME \
    && useradd --create-home --no-log-init --uid $UID --gid $GID $USERNAME \
    && usermod --append --groups wheel $USERNAME \
    && echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers


RUN dnf update -y \
    && dnf upgrade -y \
    && dnf install -y \
    which \
    git \
    gtk4-devel \
    gcc \ 
    ripgrep \ 
    fd-find \
    && dnf clean -y all

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && \
    rm -rf /opt/nvim && \
    tar -C /opt -xzf nvim-linux-x86_64.tar.gz && \
    rm nvim-linux-x86_64.tar.gz

USER $USERNAME

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile complete --component cargo,clippy,rls,rust-analysis,rust-analyzer,rust-src,rust-std,rustc,rustfmt

ENV PATH="$PATH:$HOME/.cargo/bin:/opt/nvim-linux-x86_64/bin"
